name: Run Scraper - Update data # 워크플로우 이름 지정

on: #[push]
  schedule:
    - cron:  '0 0/6 * * *' # 주기적으로 실행하기 위한 스케줄링 - cron 설정

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
          python-version: '3.x'
          architecture: 'x64'
    - name: install oracle client
      run: |
        sudo add-apt-repository universe
        sudo apt update 
        sudo apt install alien
        sudo alien -i oracle-instantclient19.10-basic-19.10.0.0.0-1.x86_64.rpm
        sudo sh -c "echo /usr/lib/oracle/19.10/client64/lib > /etc/ld.so.conf.d/oracle-instantclient.conf"
        sudo ldconfig
        export LD_LIBRARY_PATH=/usr/lib/oracle/19.10/client64/lib:$LD_LIBRARY_PATH
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install cx_Oracle
        python -m pip install cx_Oracle --upgrade
        pip freeze > requirements.txt
    - name: Install python package # 파이썬 관련 패키지를 설치
      run: |        
        pip install beautifulsoup4
        pip install requests
#    - name: go setup
#      uses: actions/setup-go@v2.1.2
#      with:
#       go-version: "1.13"
#    - name: pg driver
#      run: |
#             go get github.com/lib/pq
    - name: Run Scraper with python
      run: |
        python "Scraper.py"
    - name: Commits
      run: |
        git config --local user.email "your@email"
        git config --local user.name "Auto_Scraping_Name" # 커밋에 포함될 이름
        git add news.json
        git commit -m "Auto - Update data with Scraping" # 커밋 메세지
    - name: Remote
      run: |
       git remote remove origin
       git remote add origin https://github.com/2021-SMHRD-KDT-AI-7/SOP/tree/master/GitTest
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        branch: 'master'
        github_token: $ 
